### ISSUE TITLE
Cannot compile jgit in Quarkus native mode

### ISSUE THREAD

**Issue by sunix** [jh-pages/jh-pages#1]
```
[jh-pages-1.0.0-SNAPSHOT-runner:491]    classlist:   6,811.62 ms,  0.96 GB
[jh-pages-1.0.0-SNAPSHOT-runner:491]        (cap):     992.05 ms,  0.96 GB
[jh-pages-1.0.0-SNAPSHOT-runner:491]        setup:   4,409.87 ms,  0.96 GB
16:17:59,166 INFO  [org.jbo.threads] JBoss Threads version 3.2.0.Final
[jh-pages-1.0.0-SNAPSHOT-runner:491]     (clinit):     767.04 ms,  1.32 GB
[jh-pages-1.0.0-SNAPSHOT-runner:491]   (typeflow):  44,487.85 ms,  1.32 GB
[jh-pages-1.0.0-SNAPSHOT-runner:491]    (objects):  57,695.64 ms,  1.32 GB
[jh-pages-1.0.0-SNAPSHOT-runner:491]   (features):   1,106.15 ms,  1.32 GB
[jh-pages-1.0.0-SNAPSHOT-runner:491]     analysis: 105,815.86 ms,  1.32 GB
Error: Unsupported features in 4 methods
Detailed message:
Error: Detected a started Thread in the image heap. Threads running in the image generator are no longer running at image runtime.  To see how this object got instantiated use --trace-object-instantiation=java.lang.Thread. The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image runtime by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Trace: Object was reached by 
        reading field java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.leader of
                constant java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue@119025b reached by 
        reading field java.util.concurrent.ThreadPoolExecutor.workQueue of
                constant java.util.concurrent.ScheduledThreadPoolExecutor@62ce4777 reached by 
        scanning method org.eclipse.jgit.lib.internal.WorkQueue.getExecutor(WorkQueue.java:71)
Call path from entry point to org.eclipse.jgit.lib.internal.WorkQueue.getExecutor(): 
        at org.eclipse.jgit.lib.internal.WorkQueue.getExecutor(WorkQueue.java:71)
        at org.eclipse.jgit.lib.BatchingProgressMonitor$Task.restartTimer(BatchingProgressMonitor.java:195)
        at org.eclipse.jgit.lib.BatchingProgressMonitor$Task.update(BatchingProgressMonitor.java:175)
        at org.eclipse.jgit.lib.BatchingProgressMonitor.update(BatchingProgressMonitor.java:61)
        at org.eclipse.jgit.internal.storage.pack.DeltaWindow.search(DeltaWindow.java:141)
        at org.eclipse.jgit.internal.storage.pack.DeltaTask.runWindow(DeltaTask.java:295)
        at org.eclipse.jgit.internal.storage.pack.DeltaTask.call(DeltaTask.java:273)
        at java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at com.oracle.svm.core.jdk.RuntimeSupport.executeHooks(RuntimeSupport.java:125)
        at com.oracle.svm.core.jdk.RuntimeSupport.executeStartupHooks(RuntimeSupport.java:75)
        at com.oracle.svm.core.JavaMainWrapper.runCore(JavaMainWrapper.java:137)
        at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:182)
        at com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)
Error: Detected a started Thread in the image heap. Threads running in the image generator are no longer running at image runtime.  To see how this object got instantiated use --trace-object-instantiation=java.lang.Thread. The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image runtime by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Trace: Object was reached by 
        reading field java.util.concurrent.ThreadPoolExecutor$Worker.thread of
                constant java.util.concurrent.ThreadPoolExecutor$Worker@1aa8b506 reached by 
        reading field java.util.HashMap$Node.key of
                constant java.util.HashMap$Node@547c64a7 reached by 
        indexing into array
                constant java.util.HashMap$Node[]@7bb74bfd reached by 
        reading field java.util.HashMap.table of
                constant java.util.HashMap@459921f7 reached by 
        reading field java.util.HashSet.map of
                constant java.util.HashSet@7319bf3d reached by 
        reading field java.util.concurrent.ThreadPoolExecutor.workers of
                constant java.util.concurrent.ScheduledThreadPoolExecutor@62ce4777 reached by 
        scanning method org.eclipse.jgit.lib.internal.WorkQueue.getExecutor(WorkQueue.java:71)
Call path from entry point to org.eclipse.jgit.lib.internal.WorkQueue.getExecutor(): 
        at org.eclipse.jgit.lib.internal.WorkQueue.getExecutor(WorkQueue.java:71)
        at org.eclipse.jgit.lib.BatchingProgressMonitor$Task.restartTimer(BatchingProgressMonitor.java:195)
        at org.eclipse.jgit.lib.BatchingProgressMonitor$Task.update(BatchingProgressMonitor.java:175)
        at org.eclipse.jgit.lib.BatchingProgressMonitor.update(BatchingProgressMonitor.java:61)
        at org.eclipse.jgit.internal.storage.pack.DeltaWindow.search(DeltaWindow.java:141)
        at org.eclipse.jgit.internal.storage.pack.DeltaTask.runWindow(DeltaTask.java:295)
        at org.eclipse.jgit.internal.storage.pack.DeltaTask.call(DeltaTask.java:273)
        at java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at com.oracle.svm.core.jdk.RuntimeSupport.executeHooks(RuntimeSupport.java:125)
        at com.oracle.svm.core.jdk.RuntimeSupport.executeStartupHooks(RuntimeSupport.java:75)
        at com.oracle.svm.core.JavaMainWrapper.runCore(JavaMainWrapper.java:137)
        at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:182)
        at com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)
Error: Detected a started Thread in the image heap. Threads running in the image generator are no longer running at image runtime.  To see how this object got instantiated use --trace-object-instantiation=java.lang.Thread. The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image runtime by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Trace: Object was reached by 
        reading field java.util.concurrent.locks.AbstractQueuedSynchronizer$Node.thread of
                constant java.util.concurrent.locks.AbstractQueuedSynchronizer$Node@4d39bdda reached by 
        reading field java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.firstWaiter of
                constant java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@1094dea0 reached by 
        reading field java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.available of
                constant java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue@119025b reached by 
        reading field java.util.concurrent.ThreadPoolExecutor.workQueue of
                constant java.util.concurrent.ScheduledThreadPoolExecutor@62ce4777 reached by 
        scanning method org.eclipse.jgit.lib.internal.WorkQueue.getExecutor(WorkQueue.java:71)
Call path from entry point to org.eclipse.jgit.lib.internal.WorkQueue.getExecutor(): 
        at org.eclipse.jgit.lib.internal.WorkQueue.getExecutor(WorkQueue.java:71)
        at org.eclipse.jgit.lib.BatchingProgressMonitor$Task.restartTimer(BatchingProgressMonitor.java:195)
        at org.eclipse.jgit.lib.BatchingProgressMonitor$Task.update(BatchingProgressMonitor.java:175)
        at org.eclipse.jgit.lib.BatchingProgressMonitor.update(BatchingProgressMonitor.java:61)
        at org.eclipse.jgit.internal.storage.pack.DeltaWindow.search(DeltaWindow.java:141)
        at org.eclipse.jgit.internal.storage.pack.DeltaTask.runWindow(DeltaTask.java:295)
        at org.eclipse.jgit.internal.storage.pack.DeltaTask.call(DeltaTask.java:273)
        at java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at com.oracle.svm.core.jdk.RuntimeSupport.executeHooks(RuntimeSupport.java:125)
        at com.oracle.svm.core.jdk.RuntimeSupport.executeStartupHooks(RuntimeSupport.java:75)
        at com.oracle.svm.core.JavaMainWrapper.runCore(JavaMainWrapper.java:137)
        at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:182)
        at com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)
Error: No instances of sun.security.provider.NativePRNG are allowed in the image heap as this class should be initialized at image runtime. To see how this object got instantiated use --trace-object-instantiation=sun.security.provider.NativePRNG.
Trace: Object was reached by 
        reading field java.security.SecureRandom.secureRandomSpi of
                constant java.security.SecureRandom@21c5130e reached by 
        scanning method org.eclipse.jgit.transport.HttpAuthMethod$Digest.<init>(HttpAuthMethod.java:310)
Call path from entry point to org.eclipse.jgit.transport.HttpAuthMethod$Digest.<init>(String): 
        at org.eclipse.jgit.transport.HttpAuthMethod$Digest.<init>(HttpAuthMethod.java:304)
        at org.eclipse.jgit.transport.HttpAuthMethod$Type$3.method(HttpAuthMethod.java:77)
        at org.eclipse.jgit.transport.HttpAuthMethod.scanResponse(HttpAuthMethod.java:158)
        at org.eclipse.jgit.transport.TransportHttp$Service.sendRequest(TransportHttp.java:1696)
        at org.eclipse.jgit.transport.TransportHttp$LongPollService.execute(TransportHttp.java:1919)
        at org.eclipse.jgit.transport.TransportHttp$Service$HttpExecuteStream.read(TransportHttp.java:1821)
        at java.io.InputStream.read(InputStream.java:205)
        at org.eclipse.jgit.util.io.StreamCopyThread.run(StreamCopyThread.java:94)
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:519)
        at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
        at com.oracle.svm.core.code.IsolateEnterStub.PosixJavaThreads_pthreadStartRoutine_e1f4a8c0039f8337338252cd8734f63a79b5e3df(generated:0)

com.oracle.svm.core.util.UserError$UserException: Unsupported features in 4 methods
Detailed message:
Error: Detected a started Thread in the image heap. Threads running in the image generator are no longer running at image runtime.  To see how this object got instantiated use --trace-object-instantiation=java.lang.Thread. The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image runtime by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Trace: Object was reached by 
        reading field java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.leader of
                constant java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue@119025b reached by 
        reading field java.util.concurrent.ThreadPoolExecutor.workQueue of
                constant java.util.concurrent.ScheduledThreadPoolExecutor@62ce4777 reached by 
        scanning method org.eclipse.jgit.lib.internal.WorkQueue.getExecutor(WorkQueue.java:71)
Call path from entry point to org.eclipse.jgit.lib.internal.WorkQueue.getExecutor(): 
        at org.eclipse.jgit.lib.internal.WorkQueue.getExecutor(WorkQueue.java:71)
        at org.eclipse.jgit.lib.BatchingProgressMonitor$Task.restartTimer(BatchingProgressMonitor.java:195)
        at org.eclipse.jgit.lib.BatchingProgressMonitor$Task.update(BatchingProgressMonitor.java:175)
        at org.eclipse.jgit.lib.BatchingProgressMonitor.update(BatchingProgressMonitor.java:61)
        at org.eclipse.jgit.internal.storage.pack.DeltaWindow.search(DeltaWindow.java:141)
        at org.eclipse.jgit.internal.storage.pack.DeltaTask.runWindow(DeltaTask.java:295)
        at org.eclipse.jgit.internal.storage.pack.DeltaTask.call(DeltaTask.java:273)
        at java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at com.oracle.svm.core.jdk.RuntimeSupport.executeHooks(RuntimeSupport.java:125)
        at com.oracle.svm.core.jdk.RuntimeSupport.executeStartupHooks(RuntimeSupport.java:75)
        at com.oracle.svm.core.JavaMainWrapper.runCore(JavaMainWrapper.java:137)
        at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:182)
        at com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)
Error: Detected a started Thread in the image heap. Threads running in the image generator are no longer running at image runtime.  To see how this object got instantiated use --trace-object-instantiation=java.lang.Thread. The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image runtime by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Trace: Object was reached by 
        reading field java.util.concurrent.ThreadPoolExecutor$Worker.thread of
                constant java.util.concurrent.ThreadPoolExecutor$Worker@1aa8b506 reached by 
        reading field java.util.HashMap$Node.key of
                constant java.util.HashMap$Node@547c64a7 reached by 
        indexing into array
                constant java.util.HashMap$Node[]@7bb74bfd reached by 
        reading field java.util.HashMap.table of
                constant java.util.HashMap@459921f7 reached by 
        reading field java.util.HashSet.map of
                constant java.util.HashSet@7319bf3d reached by 
        reading field java.util.concurrent.ThreadPoolExecutor.workers of
                constant java.util.concurrent.ScheduledThreadPoolExecutor@62ce4777 reached by 
        scanning method org.eclipse.jgit.lib.internal.WorkQueue.getExecutor(WorkQueue.java:71)
Call path from entry point to org.eclipse.jgit.lib.internal.WorkQueue.getExecutor(): 
        at org.eclipse.jgit.lib.internal.WorkQueue.getExecutor(WorkQueue.java:71)
        at org.eclipse.jgit.lib.BatchingProgressMonitor$Task.restartTimer(BatchingProgressMonitor.java:195)
        at org.eclipse.jgit.lib.BatchingProgressMonitor$Task.update(BatchingProgressMonitor.java:175)
        at org.eclipse.jgit.lib.BatchingProgressMonitor.update(BatchingProgressMonitor.java:61)
        at org.eclipse.jgit.internal.storage.pack.DeltaWindow.search(DeltaWindow.java:141)
        at org.eclipse.jgit.internal.storage.pack.DeltaTask.runWindow(DeltaTask.java:295)
        at org.eclipse.jgit.internal.storage.pack.DeltaTask.call(DeltaTask.java:273)
        at java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at com.oracle.svm.core.jdk.RuntimeSupport.executeHooks(RuntimeSupport.java:125)
        at com.oracle.svm.core.jdk.RuntimeSupport.executeStartupHooks(RuntimeSupport.java:75)
        at com.oracle.svm.core.JavaMainWrapper.runCore(JavaMainWrapper.java:137)
        at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:182)
        at com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)
Error: Detected a started Thread in the image heap. Threads running in the image generator are no longer running at image runtime.  To see how this object got instantiated use --trace-object-instantiation=java.lang.Thread. The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image runtime by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Trace: Object was reached by 
        reading field java.util.concurrent.locks.AbstractQueuedSynchronizer$Node.thread of
                constant java.util.concurrent.locks.AbstractQueuedSynchronizer$Node@4d39bdda reached by 
        reading field java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.firstWaiter of
                constant java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@1094dea0 reached by 
        reading field java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.available of
                constant java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue@119025b reached by 
        reading field java.util.concurrent.ThreadPoolExecutor.workQueue of
                constant java.util.concurrent.ScheduledThreadPoolExecutor@62ce4777 reached by 
        scanning method org.eclipse.jgit.lib.internal.WorkQueue.getExecutor(WorkQueue.java:71)
Call path from entry point to org.eclipse.jgit.lib.internal.WorkQueue.getExecutor(): 
        at org.eclipse.jgit.lib.internal.WorkQueue.getExecutor(WorkQueue.java:71)
        at org.eclipse.jgit.lib.BatchingProgressMonitor$Task.restartTimer(BatchingProgressMonitor.java:195)
        at org.eclipse.jgit.lib.BatchingProgressMonitor$Task.update(BatchingProgressMonitor.java:175)
        at org.eclipse.jgit.lib.BatchingProgressMonitor.update(BatchingProgressMonitor.java:61)
        at org.eclipse.jgit.internal.storage.pack.DeltaWindow.search(DeltaWindow.java:141)
        at org.eclipse.jgit.internal.storage.pack.DeltaTask.runWindow(DeltaTask.java:295)
        at org.eclipse.jgit.internal.storage.pack.DeltaTask.call(DeltaTask.java:273)
        at java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at com.oracle.svm.core.jdk.RuntimeSupport.executeHooks(RuntimeSupport.java:125)
        at com.oracle.svm.core.jdk.RuntimeSupport.executeStartupHooks(RuntimeSupport.java:75)
        at com.oracle.svm.core.JavaMainWrapper.runCore(JavaMainWrapper.java:137)
        at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:182)
        at com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)
Error: No instances of sun.security.provider.NativePRNG are allowed in the image heap as this class should be initialized at image runtime. To see how this object got instantiated use --trace-object-instantiation=sun.security.provider.NativePRNG.
Trace: Object was reached by 
        reading field java.security.SecureRandom.secureRandomSpi of
                constant java.security.SecureRandom@21c5130e reached by 
        scanning method org.eclipse.jgit.transport.HttpAuthMethod$Digest.<init>(HttpAuthMethod.java:310)
Call path from entry point to org.eclipse.jgit.transport.HttpAuthMethod$Digest.<init>(String): 
        at org.eclipse.jgit.transport.HttpAuthMethod$Digest.<init>(HttpAuthMethod.java:304)
        at org.eclipse.jgit.transport.HttpAuthMethod$Type$3.method(HttpAuthMethod.java:77)
        at org.eclipse.jgit.transport.HttpAuthMethod.scanResponse(HttpAuthMethod.java:158)
        at org.eclipse.jgit.transport.TransportHttp$Service.sendRequest(TransportHttp.java:1696)
        at org.eclipse.jgit.transport.TransportHttp$LongPollService.execute(TransportHttp.java:1919)
        at org.eclipse.jgit.transport.TransportHttp$Service$HttpExecuteStream.read(TransportHttp.java:1821)
        at java.io.InputStream.read(InputStream.java:205)
        at org.eclipse.jgit.util.io.StreamCopyThread.run(StreamCopyThread.java:94)
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:519)
        at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
        at com.oracle.svm.core.code.IsolateEnterStub.PosixJavaThreads_pthreadStartRoutine_e1f4a8c0039f8337338252cd8734f63a79b5e3df(generated:0)

        at com.oracle.svm.core.util.UserError.abort(UserError.java:82)
        at com.oracle.svm.hosted.FallbackFeature.reportAsFallback(FallbackFeature.java:233)
        at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:773)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:563)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:476)
        at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Unsupported features in 4 methods
Detailed message:
Error: Detected a started Thread in the image heap. Threads running in the image generator are no longer running at image runtime.  To see how this object got instantiated use --trace-object-instantiation=java.lang.Thread. The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image runtime by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Trace: Object was reached by 
        reading field java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.leader of
                constant java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue@119025b reached by 
        reading field java.util.concurrent.ThreadPoolExecutor.workQueue of
                constant java.util.concurrent.ScheduledThreadPoolExecutor@62ce4777 reached by 
        scanning method org.eclipse.jgit.lib.internal.WorkQueue.getExecutor(WorkQueue.java:71)
Call path from entry point to org.eclipse.jgit.lib.internal.WorkQueue.getExecutor(): 
        at org.eclipse.jgit.lib.internal.WorkQueue.getExecutor(WorkQueue.java:71)
        at org.eclipse.jgit.lib.BatchingProgressMonitor$Task.restartTimer(BatchingProgressMonitor.java:195)
        at org.eclipse.jgit.lib.BatchingProgressMonitor$Task.update(BatchingProgressMonitor.java:175)
        at org.eclipse.jgit.lib.BatchingProgressMonitor.update(BatchingProgressMonitor.java:61)
        at org.eclipse.jgit.internal.storage.pack.DeltaWindow.search(DeltaWindow.java:141)
        at org.eclipse.jgit.internal.storage.pack.DeltaTask.runWindow(DeltaTask.java:295)
        at org.eclipse.jgit.internal.storage.pack.DeltaTask.call(DeltaTask.java:273)
        at java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at com.oracle.svm.core.jdk.RuntimeSupport.executeHooks(RuntimeSupport.java:125)
        at com.oracle.svm.core.jdk.RuntimeSupport.executeStartupHooks(RuntimeSupport.java:75)
        at com.oracle.svm.core.JavaMainWrapper.runCore(JavaMainWrapper.java:137)
        at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:182)
        at com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)
Error: Detected a started Thread in the image heap. Threads running in the image generator are no longer running at image runtime.  To see how this object got instantiated use --trace-object-instantiation=java.lang.Thread. The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image runtime by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Trace: Object was reached by 
        reading field java.util.concurrent.ThreadPoolExecutor$Worker.thread of
                constant java.util.concurrent.ThreadPoolExecutor$Worker@1aa8b506 reached by 
        reading field java.util.HashMap$Node.key of
                constant java.util.HashMap$Node@547c64a7 reached by 
        indexing into array
                constant java.util.HashMap$Node[]@7bb74bfd reached by 
        reading field java.util.HashMap.table of
                constant java.util.HashMap@459921f7 reached by 
        reading field java.util.HashSet.map of
                constant java.util.HashSet@7319bf3d reached by 
        reading field java.util.concurrent.ThreadPoolExecutor.workers of
                constant java.util.concurrent.ScheduledThreadPoolExecutor@62ce4777 reached by 
        scanning method org.eclipse.jgit.lib.internal.WorkQueue.getExecutor(WorkQueue.java:71)
Call path from entry point to org.eclipse.jgit.lib.internal.WorkQueue.getExecutor(): 
        at org.eclipse.jgit.lib.internal.WorkQueue.getExecutor(WorkQueue.java:71)
        at org.eclipse.jgit.lib.BatchingProgressMonitor$Task.restartTimer(BatchingProgressMonitor.java:195)
        at org.eclipse.jgit.lib.BatchingProgressMonitor$Task.update(BatchingProgressMonitor.java:175)
        at org.eclipse.jgit.lib.BatchingProgressMonitor.update(BatchingProgressMonitor.java:61)
        at org.eclipse.jgit.internal.storage.pack.DeltaWindow.search(DeltaWindow.java:141)
        at org.eclipse.jgit.internal.storage.pack.DeltaTask.runWindow(DeltaTask.java:295)
        at org.eclipse.jgit.internal.storage.pack.DeltaTask.call(DeltaTask.java:273)
        at java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at com.oracle.svm.core.jdk.RuntimeSupport.executeHooks(RuntimeSupport.java:125)
        at com.oracle.svm.core.jdk.RuntimeSupport.executeStartupHooks(RuntimeSupport.java:75)
        at com.oracle.svm.core.JavaMainWrapper.runCore(JavaMainWrapper.java:137)
        at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:182)
        at com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)
Error: Detected a started Thread in the image heap. Threads running in the image generator are no longer running at image runtime.  To see how this object got instantiated use --trace-object-instantiation=java.lang.Thread. The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image runtime by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Trace: Object was reached by 
        reading field java.util.concurrent.locks.AbstractQueuedSynchronizer$Node.thread of
                constant java.util.concurrent.locks.AbstractQueuedSynchronizer$Node@4d39bdda reached by 
        reading field java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.firstWaiter of
                constant java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@1094dea0 reached by 
        reading field java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.available of
                constant java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue@119025b reached by 
        reading field java.util.concurrent.ThreadPoolExecutor.workQueue of
                constant java.util.concurrent.ScheduledThreadPoolExecutor@62ce4777 reached by 
        scanning method org.eclipse.jgit.lib.internal.WorkQueue.getExecutor(WorkQueue.java:71)
Call path from entry point to org.eclipse.jgit.lib.internal.WorkQueue.getExecutor(): 
        at org.eclipse.jgit.lib.internal.WorkQueue.getExecutor(WorkQueue.java:71)
        at org.eclipse.jgit.lib.BatchingProgressMonitor$Task.restartTimer(BatchingProgressMonitor.java:195)
        at org.eclipse.jgit.lib.BatchingProgressMonitor$Task.update(BatchingProgressMonitor.java:175)
        at org.eclipse.jgit.lib.BatchingProgressMonitor.update(BatchingProgressMonitor.java:61)
        at org.eclipse.jgit.internal.storage.pack.DeltaWindow.search(DeltaWindow.java:141)
        at org.eclipse.jgit.internal.storage.pack.DeltaTask.runWindow(DeltaTask.java:295)
        at org.eclipse.jgit.internal.storage.pack.DeltaTask.call(DeltaTask.java:273)
        at java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at com.oracle.svm.core.jdk.RuntimeSupport.executeHooks(RuntimeSupport.java:125)
        at com.oracle.svm.core.jdk.RuntimeSupport.executeStartupHooks(RuntimeSupport.java:75)
        at com.oracle.svm.core.JavaMainWrapper.runCore(JavaMainWrapper.java:137)
        at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:182)
        at com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)
Error: No instances of sun.security.provider.NativePRNG are allowed in the image heap as this class should be initialized at image runtime. To see how this object got instantiated use --trace-object-instantiation=sun.security.provider.NativePRNG.
Trace: Object was reached by 
        reading field java.security.SecureRandom.secureRandomSpi of
                constant java.security.SecureRandom@21c5130e reached by 
        scanning method org.eclipse.jgit.transport.HttpAuthMethod$Digest.<init>(HttpAuthMethod.java:310)
Call path from entry point to org.eclipse.jgit.transport.HttpAuthMethod$Digest.<init>(String): 
        at org.eclipse.jgit.transport.HttpAuthMethod$Digest.<init>(HttpAuthMethod.java:304)
        at org.eclipse.jgit.transport.HttpAuthMethod$Type$3.method(HttpAuthMethod.java:77)
        at org.eclipse.jgit.transport.HttpAuthMethod.scanResponse(HttpAuthMethod.java:158)
        at org.eclipse.jgit.transport.TransportHttp$Service.sendRequest(TransportHttp.java:1696)
        at org.eclipse.jgit.transport.TransportHttp$LongPollService.execute(TransportHttp.java:1919)
        at org.eclipse.jgit.transport.TransportHttp$Service$HttpExecuteStream.read(TransportHttp.java:1821)
        at java.io.InputStream.read(InputStream.java:205)
        at org.eclipse.jgit.util.io.StreamCopyThread.run(StreamCopyThread.java:94)
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:519)
        at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
        at com.oracle.svm.core.code.IsolateEnterStub.PosixJavaThreads_pthreadStartRoutine_e1f4a8c0039f8337338252cd8734f63a79b5e3df(generated:0)

        at com.oracle.graal.pointsto.constraints.UnsupportedFeatures.report(UnsupportedFeatures.java:129)
        at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:770)
        ... 8 more
Error: Image build request failed with exit status 1
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:11 min
[INFO] Finished at: 2021-04-23T16:19:03Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:1.13.0.Final:build (default) on project jh-pages: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR]         [error]: Build step io.quarkus.deployment.pkg.steps.NativeImageBuildStep#build threw an exception: java.lang.RuntimeException: Failed to build native image
[ERROR]         at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.build(NativeImageBuildStep.java:209)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[ERROR]         at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:920)
[ERROR]         at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2415)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
[ERROR]         at java.base/java.lang.Thread.run(Thread.java:834)
[ERROR]         at org.jboss.threads.JBossThread.run(JBossThread.java:501)
[ERROR] Caused by: java.lang.RuntimeException: Image generation failed. Exit code: 1
[ERROR]         at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.imageGenerationFailed(NativeImageBuildStep.java:350)
[ERROR]         at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.build(NativeImageBuildStep.java:181)
[ERROR]         ... 10 more
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

**Comment by sunix** [comment]
From Sebi:
use
```
<dependency>
    <groupId>io.quarkus</groupId>
    <artifactId>quarkus-jgit</artifactId>
</dependency>
```

**Comment by sunix** [comment]
Fixed with https://github.com/jh-pages/jh-pages/commit/83f456694ae246d877cc526471385d3bdedfa799
